### PR TITLE
Added commands for Keep showing/Stop showing and styling to options page

### PR DESCRIPTION
**Pull request by DNCrane**

### CODE REVIEW

**Comment by aerovistae** [comment]
Hi guys, I had just moved to Chicago, hence large delay in continuing work. But I'm back on it now.

I checked out the pull request today and can't merge it as is-- check out google.com with the extension active! At least for me, google's main image is hidden now.

You can't include bootstrap.css as a content script-- it gets inserted into EVERY PAGE IN THE BROWSER, which would HEAVILY mess with styling not to mention slow down the loading times for every page the user visited.

You'll need to style options.html without using bootstrap. I mean, given what you've got in that page, it's really not needed anyway. Send me another pull request whenever! I'll get on it much faster.

**Comment by aerovistae** [comment]
(Oh, you actually don't have to send a new pull request, I forgot it will update this one automatically when you push.)

**Comment by DNCrane** [comment]
Good catch. It looks like you can still use the css file in the options page without adding it to content scripts -- I removed it and it's still working.

**Comment by aerovistae** [comment]
Oh, didn't know that. Cool. I'll check it out again when I get home tonight.

**Pull request merged**
